targets:
  $default:
    builders:
      typed_sql|typed_sql:
        enabled: true
        generate_for:
         - 'test/**.dart'
         - 'example/lib/src/model.dart'
      typed_sql|typed_sql_extensions:
        enabled: true
        generate_for:
         - 'lib/src/typed_sql.dart'
builders:
  typed_sql:
    import: "package:typed_sql/builder.dart"
    builder_factories: ["typedSqlBuilder"]
    build_extensions: {"$package$": [".typed_sql.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
  typed_sql_extensions:
    import: "package:typed_sql/src/codegen/extension_builder.dart"
    builder_factories: ["typedSqlExtensionBuilder"]
    build_extensions: {".dart": [".typed_sql_extensions.g.part"]}
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
